services:
  - type: web
    name: grano-fino-api
    runtime: python
    plan: free # Nivel gratuito: 512 MB RAM
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
